### ISSUE TITLE
duplicate files

### ISSUE THREAD

**Issue by larshp** [pixelbaker/ABAP-RayTracer#31]
Hi,
Looks like
https://github.com/pixelbaker/ABAP-RayTracer/blob/master/src/lab/zart_display_image_test.prog.abap
and
https://github.com/pixelbaker/ABAP-RayTracer/blob/master/src/zart_display_image_test.prog.abap
are identical, can you help removing one of them?

**Comment by pixelbaker** [comment]
Hi Lars, 
damn you are a good observer.
I am not happy with this repo state myself, but I have the situation that I am using SAP GUI for Java, which results into a problem with abapGit which tells me "process_state_list: empty list" after I told it to remove the four files.
I read about the bug and I know about the focus is not on supporting SAP GUI for Java, which I fully support.
I need to get myself a Windows OS with SAP GUI for Windows and do the commit from there.
Or, can you create a pull request in which you are committing the deletion?
Ultimately I guess I want my own SAP GUI for Windows I guess. 

Have a great Sunday,
André (rhymes 😄) 

<img width="1405" alt="Screenshot 2019-06-16 at 14 16 12" src="https://user-images.githubusercontent.com/29891579/59564015-b4141600-9041-11e9-9b40-45f1e3a70733.png">

**Comment by larshp** [comment]
or just use any git client to remove the 4 files, this can also be done via the github web ui, https://help.github.com/en/articles/deleting-files

got a duplicate check running for all the abap open source code, to make sure there are no overlapping file names, which will result in conflicts, see https://travis-ci.org/dotabap/dotabap-list

**Comment by pixelbaker** [comment]
So easy, with Github. Thanks for the hint. And thanks for having my back with your CI job.
Duplicate files have been deleted.
